---
version: "2.0"

services:
  whisper-api:
    image: kylecohen01/whisper-transcription-api:1.6
    expose:
      - port: 3333
        as: 80
        to:
          - global: true
        http_options:
          max_body_size: 4294967295
          read_timeout: 3600000
          send_timeout: 600000
          next_cases:
            - error
            - timeout
          next_tries: 3
          next_timeout: 600000
    params:
      storage:
        models:
          mount: /app/models
          readOnly: false
    env:
      - PYTHONUNBUFFERED=1
      - HUGGINGFACE_TOKEN=your_token_here
      - WHISPERX_COMPUTE_TYPE=float32
      - WHISPERX_BATCH_SIZE=8
      - WHISPERX_CHAR_ALIGN=true
      - MAX_CONCURRENT_REQUESTS=4
      - MEMORY_PER_REQUEST_GB=6.0
      - WHISPERX_CHUNK_LENGTH=15
      - VAD_ONSET=0.500
      - VAD_OFFSET=0.200
      - ALIGN_MODEL=WAV2VEC2_ASR_LARGE_LV60K_960H
      - INTERPOLATE_METHOD=linear
      - SEGMENT_RESOLUTION=sentence
      - ENABLE_REQUEST_QUEUING=true
      - QUEUE_TIMEOUT=300

profiles:
  compute:
    whisper-api:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 16Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx4090
                - model: rtx3090
                - model: a6000
                - model: v100
        storage:
          - size: 50Gi
            name: models
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        whisper-api: 
          denom: uakt
          amount: 6000

deployment:
  whisper-api:
    dcloud:
      profile: whisper-api
      count: 1 