---
version: "2.0"

services:
  whisper-api:
    image: your-dockerhub-username/whisper-transcription-api:latest
    expose:
      - port: 3333
        as: 80
        to:
          - global: true
    params:
      storage:
        models:
          mount: /app/models
          readOnly: false
    env:
      - "PYTHONUNBUFFERED=1"
      - "CUDA_VISIBLE_DEVICES="

profiles:
  compute:
    whisper-api:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 8Gi
        storage:
          - size: 25Gi
            name: models
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        whisper-api: 
          denom: uakt
          amount: 1500

deployment:
  whisper-api:
    dcloud:
      profile: whisper-api
      count: 1 